config/routes.rb
Rails.application.routes.draw do
  resources :poojas

  devise_for :temples
  devise_for :users

  root 'pages#home'
  get 'pages/about' => 'pages#about'

end

app/models/pooja.rb
class Pooja < ActiveRecord::Base
end

app/models/temple.rb
class Temple < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def home
		if current_user
			redirect_to poojas_path
		end
	end
	def about
	end
end

app/controllers/poojas_controller.rb
class PoojasController < ApplicationController
  before_action :set_pooja, only: [:show, :edit, :update, :destroy]

  # GET /poojas
  # GET /poojas.json
  def index
    @poojas = Pooja.all
  end

  # GET /poojas/1
  # GET /poojas/1.json
  def show
  end

  # GET /poojas/new
  def new
    @pooja = Pooja.new
  end

  # GET /poojas/1/edit
  def edit
  end

  # POST /poojas
  # POST /poojas.json
  def create
    @pooja = Pooja.new(pooja_params)

    respond_to do |format|
      if @pooja.save
        format.html { redirect_to @pooja, notice: 'Pooja was successfully created.' }
        format.json { render :show, status: :created, location: @pooja }
      else
        format.html { render :new }
        format.json { render json: @pooja.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /poojas/1
  # PATCH/PUT /poojas/1.json
  def update
    respond_to do |format|
      if @pooja.update(pooja_params)
        format.html { redirect_to @pooja, notice: 'Pooja was successfully updated.' }
        format.json { render :show, status: :ok, location: @pooja }
      else
        format.html { render :edit }
        format.json { render json: @pooja.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /poojas/1
  # DELETE /poojas/1.json
  def destroy
    @pooja.destroy
    respond_to do |format|
      format.html { redirect_to poojas_url, notice: 'Pooja was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pooja
      @pooja = Pooja.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pooja_params
      params.require(:pooja).permit(:name, :idol, :description, :price, :availability)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/poojas_helper.rb
module PoojasHelper
end

app/views/layouts/_header.html.erb
<div class="container-fluid">
<!-- Brand and toggle get grouped for better mobile display -->
<div class="navbar-header">
<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
<span class="sr-only">Toggle navigation</span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</button>
<%= link_to "Hindu-Life", root_path, class: "navbar-brand" %>
</div>
 
<!-- Collect the nav links, forms, and other content for toggling -->
<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">


<ul class="nav navbar-nav navbar-right">
<li class="dropdown">
<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Temples<span class="caret"></span></a>
<ul class="dropdown-menu" role="menu">
<li><a href="#">Vishnu</a></li>
<li><a href="#">Ganesha</a></li>
<li><a href="#">Shiva</a></li>
<li class="divider"></li>
<li><a href="#">Pooja's At home</a></li>
</ul>
</li>
<li><%= link_to "About", pages_about_path %></li>
<% if current_user %>
<li><%= link_to "Settings", "#" %></li>
<li><%= link_to "LogOut", destroy_user_session_path, method: :delete %></li>
<% else %>
<li><%= link_to "Login", new_user_session_path %></li>
<% end %>
</ul>
</div><!-- /.navbar-collapse -->
</div><!-- /.container-fluid -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hl</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render "layouts/header" %>
<div class = "container">
<%= yield %>
</div>

</body>
</html>

app/views/pages/about.html.erb
<h1>About us ;-) </h1>

app/views/pages/home.html.erb
<br>
<div class ="jumbotron">
<h1>Hindu Life</h1>
<p>Change the way your life function by being in tune with the hindu way of life</p>
<%= link_to "Sign Up", new_user_registration_path, class: "btn btn-warning btn-lg" %>
</div>

app/views/poojas/_form.html.erb
<%= simple_form_for(@pooja) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :idol %>
    <%= f.input :description %>
    <%= f.input :price %>
    <%= f.input :availability %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/poojas/edit.html.erb
<h1>Editing Pooja</h1>

<%= render 'form' %>

<%= link_to 'Show', @pooja %> |
<%= link_to 'Back', poojas_path %>

app/views/poojas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Poojas</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Idol</th>
      <th>Description</th>
      <th>Price</th>
      <th>Availability</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @poojas.each do |pooja| %>
      <tr>
        <td><%= pooja.name %></td>
        <td><%= pooja.idol %></td>
        <td><%= pooja.description %></td>
        <td><%= pooja.price %></td>
        <td><%= pooja.availability %></td>
        <td><%= link_to 'Show', pooja %></td>
        <td><%= link_to 'Edit', edit_pooja_path(pooja) %></td>
        <td><%= link_to 'Destroy', pooja, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pooja', new_pooja_path %>

app/views/poojas/new.html.erb
<h1>New Pooja</h1>

<%= render 'form' %>

<%= link_to 'Back', poojas_path %>

app/views/poojas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pooja.name %>
</p>

<p>
  <strong>Idol:</strong>
  <%= @pooja.idol %>
</p>

<p>
  <strong>Description:</strong>
  <%= @pooja.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @pooja.price %>
</p>

<p>
  <strong>Availability:</strong>
  <%= @pooja.availability %>
</p>

<%= link_to 'Edit', edit_pooja_path(@pooja) %> |
<%= link_to 'Back', poojas_path %>